/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber;

import java.io.FileNotFoundException;
import java.util.List;

/**
 *
 * @author user
 */
public class TebakKata extends javax.swing.JFrame {
    
    WordModel modelWord;
    List<WordModel> bankSoal;

    /**
     * Creates new form TebakKata
     * @throws java.io.FileNotFoundException
     */
    public TebakKata() {
        bankSoal = WordQuestionGenerator.createQuestionInCollection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButtonMulai = new javax.swing.JButton();
        TextFieldSoal = new javax.swing.JTextField();
        ButtonCekJawaban = new javax.swing.JButton();
        LabelComment = new javax.swing.JLabel();
        soalLabel = new javax.swing.JLabel();
        ButtonBantuan = new javax.swing.JButton();
        labelHint = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\tebakgunung.jpg")); // NOI18N

        ButtonMulai.setText("Mulai");
        ButtonMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMulaiActionPerformed(evt);
            }
        });

        TextFieldSoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldSoalActionPerformed(evt);
            }
        });

        ButtonCekJawaban.setText("Yakin?");
        ButtonCekJawaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCekJawabanActionPerformed(evt);
            }
        });

        LabelComment.setText("jLabel");

        ButtonBantuan.setText("Bantuan");
        ButtonBantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBantuanActionPerformed(evt);
            }
        });

        labelHint.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(ButtonMulai)
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldSoal)
                            .addComponent(soalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelComment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonCekJawaban)
                                .addGap(0, 191, Short.MAX_VALUE))
                            .addComponent(labelHint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonBantuan)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(soalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFieldSoal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(ButtonMulai)
                        .addGap(26, 26, 26)
                        .addComponent(ButtonBantuan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCekJawaban)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelComment, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelHint, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMulaiActionPerformed
        // TODO add xyour handling code here:
        int soalIndex = (int) Math.floor(Math.random()* bankSoal.size());
        modelWord = bankSoal.get(soalIndex);
        soalLabel.setText(modelWord.acakHuruf());
        
        LabelComment.setText("");
        labelHint.setText("");
        TextFieldSoal.setText("");
        
    }//GEN-LAST:event_ButtonMulaiActionPerformed

    private void ButtonCekJawabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCekJawabanActionPerformed
        // TODO add your handling code here:
        String jawaban =  TextFieldSoal.getText().trim();
        modelWord.setJawaban(jawaban);
        if (modelWord.cekJawaban()) {
            LabelComment.setText("Hebat Cuy !");
            
        } else { 
            LabelComment.setText("Ayo tebak lagi !");
        }
    }//GEN-LAST:event_ButtonCekJawabanActionPerformed

    private void ButtonBantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBantuanActionPerformed
        labelHint.setText(modelWord.getHint());
    }//GEN-LAST:event_ButtonBantuanActionPerformed

    private void TextFieldSoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldSoalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldSoalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakKata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBantuan;
    private javax.swing.JButton ButtonCekJawaban;
    private javax.swing.JButton ButtonMulai;
    private javax.swing.JLabel LabelComment;
    private javax.swing.JTextField TextFieldSoal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelHint;
    private javax.swing.JLabel soalLabel;
    // End of variables declaration//GEN-END:variables
}
